package io.zksync.utils.smart.account;

import io.zksync.transaction.type.Transaction712;

import java.util.List;

public interface ISignPayload {
    /**
     * Signs the `payload` using multiple ECDSA private keys.
     * The signature is generated by concatenating signatures created by signing with each key individually.
     * The length of the resulting signature should be `secrets.length * 65 + 2`.
     *
     * @param payload The payload that needs to be signed.
     * @param secrets The list of the ECDSA private keys.
     * @param chainId Chain id used for initializing credentials for signing.
     */
    String sign(Transaction712 payload, List<String> secrets, long chainId);
}
